# RRNET - FreeRADIUS clients

client localhost {
  ipaddr = 127.0.0.1
  secret = rrnet-dev-radius-secret
  require_message_authenticator = yes
}

# SPECIFIC ROUTER CLIENTS (Sealed with BlastRADIUS protection)
client router-zamzam-v7-5 {
  ipaddr = 10.10.20.12
  secret = rrnet-dev-radius-secret
  require_message_authenticator = yes
}

client router-zamzam-v7-4 {
  ipaddr = 10.10.20.11
  secret = rrnet-dev-radius-secret
  require_message_authenticator = yes
}

# Fallback for other private nets
client private-nets {
  ipaddr = 10.0.0.0/8
  secret = rrnet-dev-radius-secret
  require_message_authenticator = yes
}


